export const GET_ACTIVITY_COMMENTS_REQUEST = 'GET_ACTIVITY_COMMENTS_REQUEST'
export const GET_ACTIVITY_COMMENTS_SUCCESS = 'GET_ACTIVITY_COMMENTS_SUCCESS'
export const GET_ACTIVITY_COMMENTS_FAIL = 'GET_ACTIVITY_COMMENTS_FAIL'

export const ADD_ACTIVITY_COMMENT_REQUEST = 'ADD_ACTIVITY_COMMENT_REQUEST'
export const ADD_ACTIVITY_COMMENT_SUCCESS = 'ADD_ACTIVITY_COMMENT_SUCCESS'
export const ADD_ACTIVITY_COMMENT_FAIL = 'ADD_ACTIVITY_COMMENT_FAIL'
export const ADD_ACTIVITY_COMMENT_RESET = 'ADD_ACTIVITY_COMMENT_RESET'


export const DELETE_ACTIVITY_COMMENT_REQUEST = 'DELETE_ACTIVITY_COMMENT_REQUEST'
export const DELETE_ACTIVITY_COMMENT_SUCCESS = 'DELETE_ACTIVITY_COMMENT_SUCCESS'
export const DELETE_ACTIVITY_COMMENT_FAIL = 'DELETE_ACTIVITY_COMMENT_FAIL'
export const DELETE_ACTIVITY_COMMENT_RESET = 'DELETE_ACTIVITY_COMMENT_RESET'

export const UPDATE_ACTIVITY_COMMENT_REQUEST = 'UPDATE_ACTIVITY_COMMENT_REQUEST'
export const UPDATE_ACTIVITY_COMMENT_SUCCESS = 'UPDATE_ACTIVITY_COMMENT_SUCCESS'
export const UPDATE_ACTIVITY_COMMENT_FAIL = 'UPDATE_ACTIVITY_COMMENT_FAIL'
export const UPDATE_ACTIVITY_COMMENT_RESET = 'UPDATE_ACTIVITY_COMMENT_RESET'


export const GET_ACTIVITY_COMMENTS_BY_USER_REQUEST = 'GET_ACTIVITY_COMMENTS_BY_USER_REQUEST'
export const GET_ACTIVITY_COMMENTS_BY_USER_SUCCESS = 'GET_ACTIVITY_COMMENTS_BY_USER_SUCCESS'
export const GET_ACTIVITY_COMMENTS_BY_USER_FAIL = 'GET_ACTIVITY_COMMENTS_BY_USER_FAIL'
