export const GET_ALL_ACTIVITY_REQUEST = 'GET_ALL_ACTIVITY_REQUEST'
export const GET_ALL_ACTIVITY_SUCCESS = 'GET_ALL_ACTIVITY_SUCCESS'
export const GET_ALL_ACTIVITY_FAIL = 'GET_ALL_ACTIVITY_FAIL'


export const GET_ACTIVITY_DETAILS_REQUEST = 'GET_ACTIVITY_DETAILS_REQUEST'
export const GET_ACTIVITY_DETAILS_SUCCESS = 'GET_ACTIVITY_DETAILS_SUCCESS'
export const GET_ACTIVITY_DETAILS_FAIL = 'GET_ACTIVITY_DETAILS_FAIL'

