export const GET_ALL_ACTIVITY_REQUEST = 'GET_ALL_ACTIVITY_REQUEST'
export const GET_ALL_ACTIVITY_SUCCESS = 'GET_ALL_ACTIVITY_SUCCESS'
export const GET_ALL_ACTIVITY_FAIL = 'GET_ALL_ACTIVITY_FAIL'


export const GET_ACTIVITY_DETAILS_REQUEST = 'GET_ACTIVITY_DETAILS_REQUEST'
export const GET_ACTIVITY_DETAILS_SUCCESS = 'GET_ACTIVITY_DETAILS_SUCCESS'
export const GET_ACTIVITY_DETAILS_FAIL = 'GET_ACTIVITY_DETAILS_FAIL'

export const JOIN_ACTIVITY_REQUEST = 'JOIN_ACTIVITY_REQUEST'
export const JOIN_ACTIVITY_SUCCESS = 'JOIN_ACTIVITY_SUCCESS'
export const JOIN_ACTIVITY_FAIL = 'JOIN_ACTIVITY_FAIL'
export const JOIN_ACTIVITY_RESET = 'JOIN_ACTIVITY_RESET'

export const LEAVE_ACTIVITY_REQUEST = 'LEAVE_ACTIVITY_REQUEST'
export const LEAVE_ACTIVITY_SUCCESS = 'LEAVE_ACTIVITY_SUCCESS'
export const LEAVE_ACTIVITY_FAIL = 'LEAVE_ACTIVITY_FAIL'
export const LEAVE_ACTIVITY_RESET = 'LEAVE_ACTIVITY_RESET'

export const GET_ACTIVITY_USERS_REQUEST = 'GET_ACTIVITY_USERS_REQUEST'
export const GET_ACTIVITY_USERS_SUCCESS = 'GET_ACTIVITY_USERS_SUCCESS'
export const GET_ACTIVITY_USERS_FAIL = 'GET_ACTIVITY_USERS_FAIL'

export const CHECK_USER_JOINED_REQUEST = 'CHECK_USER_JOINED_REQUEST'
export const CHECK_USER_JOINED_SUCCESS = 'CHECK_USER_JOINED_SUCCESS'
export const CHECK_USER_JOINED_FAIL = 'CHECK_USER_JOINED_FAIL'

