export const GET_ALL_ANNOUNCEMENT_REQUEST = 'GET_ALL_ANNOUNCEMENT_REQUEST'
export const GET_ALL_ANNOUNCEMENT_SUCCESS = 'GET_ALL_ANNOUNCEMENT_SUCCESS'
export const GET_ALL_ANNOUNCEMENT_FAIL = 'GET_ALL_ANNOUNCEMENT_FAIL'

