
export const SEND_COMPLAIN_REQUEST = 'SEND_COMPLAIN_REQUEST'
export const SEND_COMPLAIN_SUCCESS = 'SEND_COMPLAIN_SUCCESS'
export const SEND_COMPLAIN_FAIL = 'SEND_COMPLAIN_FAIL'
export const SEND_COMPLAIN_RESET = 'SEND_COMPLAIN_RESET'