export const PAY_SUBSCRIPTION_REQUEST = 'PAY_SUBSCRIPTION_REQUEST'
export const PAY_SUBSCRIPTION_SUCCESS = 'PAY_SUBSCRIPTION_SUCCESS'
export const PAY_SUBSCRIPTION_FAIL = 'PAY_SUBSCRIPTION_FAIL'

export const DONATE_REQUEST = 'DONATE_REQUEST'
export const DONATE_SUCCESS = 'DONATE_SUCCESS'
export const DONATE_FAIL = 'DONATE_FAIL'
export const DONATE_RESET = 'DONATE_RESET'