export const SEND_POST_REQUEST = 'SEND_POST_REQUEST'
export const SEND_POST_SUCCESS = 'SEND_POST_SUCCESS'
export const SEND_POST_FAIL = 'SEND_POST_FAIL'
export const SEND_POST_RESET = 'SEND_POST_RESET'

export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST'
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS'
export const GET_ALL_POST_FAIL = 'GET_ALL_POST_FAIL'

export const GET_ALL_POST_WITH_PAGE_REQUEST = 'GET_ALL_POST_WITH_PAGE_REQUEST'
export const GET_ALL_POST_WITH_PAGE_SUCCESS = 'GET_ALL_POST_WITH_PAGE_SUCCESS'
export const GET_ALL_POST_WITH_PAGE_FAIL = 'GET_ALL_POST_WITH_PAGE_FAIL'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'
export const DELETE_POST_RESET = 'DELETE_POST_RESET'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'
export const UPDATE_POST_RESET = 'UPDATE_POST_RESET'
