export const GET_ALL_SUBSCRIPTION_REQUEST = 'GET_ALL_SUBSCRIPTION_REQUEST'
export const GET_ALL_SUBSCRIPTION_SUCCESS = 'GET_ALL_SUBSCRIPTION_SUCCESS'
export const GET_ALL_SUBSCRIPTION_FAIL = 'GET_ALL_SUBSCRIPTION_FAIL'

export const GET_SINGLE_SUBSCRIPTION_REQUEST = 'GET_SINGLE_SUBSCRIPTION_REQUEST'
export const GET_SINGLE_SUBSCRIPTION_SUCCESS = 'GET_SINGLE_SUBSCRIPTION_SUCCESS'
export const GET_SINGLE_SUBSCRIPTION_FAIL = 'GET_SINGLE_SUBSCRIPTION_FAIL'

