export const ADD_ACTIVITY_REQUEST = 'ADD_ACTIVITY_REQUEST'
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS'
export const ADD_ACTIVITY_FAIL = 'ADD_ACTIVITY_FAIL'
export const ADD_ACTIVITY_RESET = 'ADD_ACTIVITY_RESET'


export const GET_ALL_ACTIVITY_REQUEST = 'GET_ALL_ACTIVITY_REQUEST'
export const GET_ALL_ACTIVITY_SUCCESS = 'GET_ALL_ACTIVITY_SUCCESS'
export const GET_ALL_ACTIVITY_FAIL = 'GET_ALL_ACTIVITY_FAIL'


export const UPDATE_ACTIVITY_REQUEST = 'UPDATE_ACTIVITY_REQUEST'
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS'
export const UPDATE_ACTIVITY_FAIL = 'UPDATE_ACTIVITY_FAIL'
export const UPDATE_ACTIVITY_RESET = 'UPDATE_ACTIVITY_RESET'

export const DELETE_ACTIVITY_REQUEST = 'DELETE_ACTIVITY_REQUEST'
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS'
export const DELETE_ACTIVITY_FAIL = 'DELETE_ACTIVITY_FAIL'
export const DELETE_ACTIVITY_RESET = 'DELETE_ACTIVITY_RESET'