export const ADD_ANNOUNCEMENT_REQUEST = 'ADD_ANNOUNCEMENT_REQUEST'
export const ADD_ANNOUNCEMENT_SUCCESS = 'ADD_ANNOUNCEMENT_SUCCESS'
export const ADD_ANNOUNCEMENT_FAIL = 'ADD_ANNOUNCEMENT_FAIL'
export const ADD_ANNOUNCEMENT_RESET = 'ADD_ANNOUNCEMENT_RESET'


export const GET_ALL_ANNOUNCEMENT_REQUEST = 'GET_ALL_ANNOUNCEMENT_REQUEST'
export const GET_ALL_ANNOUNCEMENT_SUCCESS = 'GET_ALL_ANNOUNCEMENT_SUCCESS'
export const GET_ALL_ANNOUNCEMENT_FAIL = 'GET_ALL_ANNOUNCEMENT_FAIL'

export const UPDATE_ANNOUNCEMENT_REQUEST = 'UPDATE_ANNOUNCEMENT_REQUEST'
export const UPDATE_ANNOUNCEMENT_SUCCESS = 'UPDATE_ANNOUNCEMENT_SUCCESS'
export const UPDATE_ANNOUNCEMENT_FAIL = 'UPDATE_ANNOUNCEMENT_FAIL'
export const UPDATE_ANNOUNCEMENT_RESET = 'UPDATE_ANNOUNCEMENT_RESET'

export const DELETE_ANNOUNCEMENT_REQUEST = 'DELETE_ANNOUNCEMENT_REQUEST'
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS'
export const DELETE_ANNOUNCEMENT_FAIL = 'DELETE_ANNOUNCEMENT_FAIL'
export const DELETE_ANNOUNCEMENT_RESET = 'DELETE_ANNOUNCEMENT_RESET'

export const GET_ALL_ANNOUNCEMENT_WITH_PAGE_REQUEST = 'GET_ALL_ANNOUNCEMENT_WITH_PAGE_REQUEST'
export const GET_ALL_ANNOUNCEMENT_WITH_PAGE_SUCCESS = 'GET_ALL_ANNOUNCEMENT_WITH_PAGE_SUCCESS'
export const GET_ALL_ANNOUNCEMENT_WITH_PAGE_FAIL = 'GET_ALL_ANNOUNCEMENT_WITH_PAGE_FAIL'