export const GET_ALL_APARTMENT_REQUEST = 'GET_ALL_APARTMENT_REQUEST'
export const GET_ALL_APARTMENT_SUCCESS = 'GET_ALL_APARTMENT_SUCCESS'
export const GET_ALL_APARTMENT_FAIL = 'GET_ALL_APARTMENT_FAIL'

export const GET_SINGLE_APARTMENT_REQUEST = 'GET_SINGLE_APARTMENT_REQUEST'
export const GET_SINGLE_APARTMENT_SUCCESS = 'GET_SINGLE_APARTMENT_SUCCESS'
export const GET_SINGLE_APARTMENT_FAIL = 'GET_SINGLE_APARTMENT_FAIL'

export const ADD_APARTMENT_REQUEST = 'ADD_APARTMENT_REQUEST'
export const ADD_APARTMENT_SUCCESS = 'ADD_APARTMENT_SUCCESS'
export const ADD_APARTMENT_FAIL = 'ADD_APARTMENT_FAIL'
export const ADD_APARTMENT_RESET = 'ADD_APARTMENT_RESET'

export const UPDATE_APARTMENT_REQUEST = 'UPDATE_APARTMENT_REQUEST'
export const UPDATE_APARTMENT_SUCCESS = 'UPDATE_APARTMENT_SUCCESS'
export const UPDATE_APARTMENT_FAIL = 'UPDATE_APARTMENT_FAIL'
export const UPDATE_APARTMENT_RESET = 'UPDATE_APARTMENT_RESET'

export const DELETE_APARTMENT_REQUEST = 'DELETE_APARTMENT_REQUEST'
export const DELETE_APARTMENT_SUCCESS = 'DELETE_APARTMENT_SUCCESS'
export const DELETE_APARTMENT_FAIL = 'DELETE_APARTMENT_FAIL'
export const DELETE_APARTMENT_RESET = 'DELETE_APARTMENT_RESET'

export const GET_APARTMENT_BY_CITY_REQUEST = 'GET_APARTMENT_BY_CITY_REQUEST'
export const GET_APARTMENT_BY_CITY_SUCCESS = 'GET_APARTMENT_BY_CITY_SUCCESS'
export const GET_APARTMENT_BY_CITY_FAIL = 'GET_APARTMENT_BY_CITY_FAIL'
