export const GET_ALL_BLOCK_REQUEST = 'GET_ALL_BLOCK_REQUEST'
export const GET_ALL_BLOCK_SUCCESS = 'GET_ALL_BLOCK_SUCCESS'
export const GET_ALL_BLOCK_FAIL = 'GET_ALL_BLOCK_FAIL'

export const GET_SINGLE_BLOCK_REQUEST = 'GET_SINGLE_BLOCK_REQUEST'
export const GET_SINGLE_BLOCK_SUCCESS = 'GET_SINGLE_BLOCK_SUCCESS'
export const GET_SINGLE_BLOCK_FAIL = 'GET_SINGLE_BLOCK_FAIL'

export const ADD_BLOCK_REQUEST = 'ADD_BLOCK_REQUEST'
export const ADD_BLOCK_SUCCESS = 'ADD_BLOCK_SUCCESS'
export const ADD_BLOCK_FAIL = 'ADD_BLOCK_FAIL'
export const ADD_BLOCK_RESET = 'ADD_BLOCK_RESET'

export const UPDATE_BLOCK_REQUEST = 'UPDATE_BLOCK_REQUEST'
export const UPDATE_BLOCK_SUCCESS = 'UPDATE_BLOCK_SUCCESS'
export const UPDATE_BLOCK_FAIL = 'UPDATE_BLOCK_FAIL'
export const UPDATE_BLOCK_RESET = 'UPDATE_BLOCK_RESET'

export const DELETE_BLOCK_REQUEST = 'DELETE_BLOCK_REQUEST'
export const DELETE_BLOCK_SUCCESS = 'DELETE_BLOCK_SUCCESS'
export const DELETE_BLOCK_FAIL = 'DELETE_BLOCK_FAIL'
export const DELETE_BLOCK_RESET = 'DELETE_BLOCK_RESET'