export const GET_ALL_COMPLAIN_REQUEST = 'GET_ALL_COMPLAIN_REQUEST'
export const GET_ALL_COMPLAIN_SUCCESS = 'GET_ALL_COMPLAIN_SUCCESS'
export const GET_ALL_COMPLAIN_FAIL = 'GET_ALL_COMPLAIN_FAIL'

export const GET_COMPLAIN_WITH_PAGE_REQUEST = 'GET_COMPLAIN_WITH_PAGE_REQUEST'
export const GET_COMPLAIN_WITH_PAGE_SUCCESS = 'GET_COMPLAIN_WITH_PAGE_SUCCESS'
export const GET_COMPLAIN_WITH_PAGE_FAIL = 'GET_COMPLAIN_WITH_PAGE_FAIL'

