export const ADD_FLAT_REQUEST = 'ADD_FLAT_REQUEST'
export const ADD_FLAT_SUCCESS = 'ADD_FLAT_SUCCESS'
export const ADD_FLAT_FAIL = 'ADD_FLAT_FAIL'
export const ADD_FLAT_RESET = 'ADD_FLAT_RESET'

export const GET_ALL_FLAT_REQUEST = 'GET_ALL_FLAT_REQUEST'
export const GET_ALL_FLAT_SUCCESS = 'GET_ALL_FLAT_SUCCESS'
export const GET_ALL_FLAT_FAIL = 'GET_ALL_FLAT_FAIL'

