export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'


export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'

export const ADD_ROLE_TO_USER_REQUEST = 'ADD_ROLE_TO_USER_REQUEST'
export const ADD_ROLE_TO_USER_SUCCESS = 'ADD_ROLE_TO_USER_SUCCESS'
export const ADD_ROLE_TO_USER_FAIL = 'ADD_ROLE_TO_USER_FAIL'
export const ADD_ROLE_TO_USER_RESET = 'ADD_ROLE_TO_USER_RESET'


